### ISSUE TITLE
Stopping a running webserver doesn't remove temp go file

### ISSUE THREAD

**Issue by sno6** [sno6/gommand#2]
If you run gommand with code that starts and runs an http server, there is no way to stop the process without killing it or stopping it through terminal signals. When doing this, the program cancels and doesn't run the clean up defer statement. Implement a way to read exit signals and then add the clean up defer block there so it can remove the file before exiting the program.

**Comment by justyntemme** [comment]
Submitted a pull request to fix issue.

**Comment by sno6** [comment]
Thanks, please check the comment on your PR.

**Comment by justyntemme** [comment]
fixed

**Comment by sno6** [comment]
Thanks:)
