### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by sno6** [sno6/gommand#6]
Help wanted.

I'm not sure how to go about testing this command-line tool. If anyone can help me or provide some ideas then that would be great:)

**Comment by dmitshur** [comment]
You can test the `run` function to ensure it executes Go code successfully and returns an expected result. See here for an example of what I mean, from my similar project:

https://github.com/shurcooL/goexec/blob/master/main_test.go

**Comment by sno6** [comment]
Thanks, that seems like a good way to do it. Nice project by the way.

**Comment by dmitshur** [comment]
> Nice project by the way.

Thanks, yours too! :)

If you're okay with it, I'll add an "Alternatives" section to my README and link to yours (see [here](https://github.com/shurcooL/vfsgen/pull/6#issue-107431054) for an example/motivation).

Also, if you find any code or ideas in goexec that you'd like to take to improve your project, feel absolutely free to do that.

**Comment by sno6** [comment]
I put this project up on Github around 10 months ago and it only had a few stars so to log in today and see 30+ more and a tweet from Rob Pike I'm a little astonished.

If you would be so kind to do so it would be much appreciated!:)

Thanks, I might take you up on that I'm going to have a good look at how you did some things now. I need to add some tests so I'm thinking of implementing a test on run like you suggested:)

**Comment by dolmen** [comment]
I just added your 2 projects in an "Alternatives" section of mine: https://github.com/dolmen-go/goeval. I would probably not have written `goeval` if I had discovered `gommand` before.

**Comment by dmitshur** [comment]
@dolmen I've sent https://github.com/shurcooL/goexec/pull/8 to add your project to goexec's Alternatives section too.

**Comment by sno6** [comment]
Cheers guys.
