### ISSUE TITLE
Add compile cache 

### ISSUE THREAD

**Issue by thomasf** [sno6/gommand#9]
The binaries could be compiled named as hashes of the input code. this would greatly make gommand more useful for repeated invocations in shell scripts or whatever.

**Comment by dolmen** [comment]
Why not just use `go build`?

**Comment by dmitshur** [comment]
This issue is from 2016. The go command added [build caching](https://golang.org/doc/go1.10#build) in Go 1.10, which came out in 2018.

But yes, it is viable to rely on `go build` for caching and being fast now, so this likely no longer needs to be implemented.
